### ISSUE TITLE
How to create a request with varying params?

### ISSUE THREAD

**Issue by gerchicov-bp** [emadhegab/MHNetwork#11]
For example in your code with `getMoviesList` I want to pass an additional param - "year".
I send the same requests but with different year value specified from outside.
How to implement it?

**Comment by emadhegab** [comment]
if i understood your request right .. then you may use 
case getMoviesList(year: string) 
then in switch you can use 
```
switch self {
        case .getMoviesList(let year):
            return .get
        }
```

**Comment by gerchicov-bp** [comment]
@emadhegab yes I did the same thing but I also modified task class:
```
class QuoteTask <T: Codable>: Operations {
    var innerRequest = RequestEnum.getMoviesList(2000) //some default request
    
    var request: Request {
        return innerRequest
    }
   ...
```

It seems you should replace inside protocol:
`var request: Request { get }`
with a property which has both set and get methods.

**Comment by emadhegab** [comment]
That will open possibility of manipulating the request after creating the task. Don’t think it’s a good practice. Unless you have a good reason for that

**Comment by gerchicov-bp** [comment]
`Operations` is just a protocol and the task is started after `execute(...)` call only.
Also apple in some libraries allows to edit properties which should be edited. For example, `UINavigationController` has `viewControllers` property with setter

**Comment by emadhegab** [comment]
Thanks you sir.. But you are comparing here apples and oranges.. viewControllers  in the navigationController are safe to manipulate .. it will not create a network issue.. it will not be hacked .. while request that comes out from a user shouldn't be modified after creating it .. to avoid manipulation and jeopardizing the app and maybe the backend
