### ISSUE TITLE
Bug in NetworkDispatcher

### ISSUE THREAD

**Issue by gerchicov-bp** [emadhegab/MHNetwork#13]
`return URLQueryItem(name: element.key, value: element.value as? String)`
This allows to pass string params only. But if you replace `element.value as? String` with `\(element.value)` it will accept for example int and bool values too.

Additionally `NetworkDispatcher` is protected from inheritance and I should create a copy of it

**Comment by emadhegab** [comment]
That's neither a but nor an issue.. Please refer to `URLQueryItem` you'll notice that value property **must** be an optional string . which make sense, since all query params treated usually as Strings not any primitive type.
